#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index_controller:
#    path: /lucky/number
#    controller: App\Controller\indexController::number

# config/routes/sonata_admin.yaml